### ISSUE TITLE
na 91.04

### ISSUE THREAD

**Issue by XelZero** [PsykoDev/Auto-Guildquest#10]
it was working perfectly fine until the update today - any way to get the old code so itll work again? or expectation before it is working on na 91.04?

**Comment by PsykoDev** [comment]
add a random opcode like " S_GUILD_QUEST_LIST = 60186 " and it's okay 
and disable guild quest logger

**Comment by Patricktheorge** [comment]
S_FIELD_EVENT_PROGRESS_INFO how to proc this
