### ISSUE TITLE
possible issue when 64 hits

### ISSUE THREAD

**Issue by XelZero** [PsykoDev/Auto-Guildquest#13]
[auto-guildquest] WARNING: Accessing deprecated "proxyAuthor"! Call stack:
[auto-guildquest] WARNING: new AutoGuildquest (C:\Users\XXXXX\AppData\Local\Programs\TeraToolbox\mods\Auto-Guildquest\index.js:17:18)

getting error on NA 32bit and per what some ppl are saying it breaks for EU 64bit - not sure if a fix is in the works or if it even matters and this is more of a useless error

**Comment by PsykoDev** [comment]
fixed
