### ISSUE TITLE
v101

### ISSUE THREAD

**Issue by XelZero** [PsykoDev/Auto-Guildquest#14]
is this still borked and you are still not playing or do you have plans for an update to get it working again?

**Comment by PsykoDev** [comment]
https://github.com/PsykoDev/Last-Def-Files
https://github.com/PsykoDev/Full-Opcode-Tera-EU-NA

no need update add all .def / .map in your Data folder and all work fine

**Comment by XelZero** [comment]
due to tb weirdness i havent done that in a while - if i have further issues ill let you know - ty

**Comment by PsykoDev** [comment]
aight thx

**Comment by XelZero** [comment]
seems to work just fine but - for some reason i can not add cards to the "card fusion" after doing that.. no idea how that makes sense but no other mod updated and adding the opmap was the only change - happening on 2 different pcs - no error just doesnt do it

**Comment by PsykoDev** [comment]
i'll check it thx maybe .def wrong

**Comment by PsykoDev** [comment]
same without TB i can't use card fusion
