### ISSUE TITLE
ERROR: Module "Auto-Guildquest" (Auto-Guildquest) could not be loaded!

### ISSUE THREAD

**Issue by Crazy-Pug** [PsykoDev/Auto-Guildquest#3]
Hello, I have that problem and it does not perform any function, I would like to know if you can help me to solve it please:
Error: [dispatch] [auto-guildquest] hook: unmapped packet "S_GUILD_QUEST_LIST"
All that comes out in red letters. Thanks since now.

**Comment by PsykoDev** [comment]
you need opcode of S_GUILD_QUEST_LIST for your region 
NA = S_GUILD_QUEST_LIST 57096
EU = S_GUILD_QUEST_LIST = 28597
