### ISSUE TITLE
S_GUILD_QUEST_LIST 57096

### ISSUE THREAD

**Issue by Darkwitt** [PsykoDev/Auto-Guildquest#4]
hello. i want to know how and where to put this opcode to make the mod works pls. If you can help me i apreciate.
Ps you have discord or something like this?

**Comment by PsykoDev** [comment]
Proxy Tera\node_modules\tera-data\map and edit your map files of your region

**Comment by Darkwitt** [comment]
ty for the help, but now it give me error in this

Error: [dispatch] [auto-guildquest] hook: unmapped packet "S_FIELD_EVENT_PROGRESS_INFO"
