### ISSUE TITLE
Error: [dispatch] [auto-guildquest] hook: unmapped packet "S_GUILD_QUEST_LIST"

### ISSUE THREAD

**Issue by Zoe975** [PsykoDev/Auto-Guildquest#7]
Heyho
pls, im to stupid maybe, but i cant handle this error.. tried to put the file S_GUILD_QUEST_LIST = 28597 into the map, but still there is an error. can u help me pls?
BTW thanx for ur nice work

**Comment by PsykoDev** [comment]
S_FIELD_EVENT_PROGRESS_INFO 25553
S_SHOW_GUILD_QUEST_LIST 31300
S_GUILD_QUEST_LIST 33691
S_UPDATE_GUILD_QUEST_STATUS 44699

**Comment by XelZero** [comment]
i updated this and still got the same error - i think it is due to not have the right def file - any ideas?

**Comment by AntiScrewdriver** [comment]
![image](https://user-images.githubusercontent.com/47073195/76577972-e77dc580-652b-11ea-890c-315a2d5a621b.png)
@XelZero mine gives the same error, no definition found

**Comment by PsykoDev** [comment]
.map files here > Proxy/Data/opcodes
.def files here > Proxy\data\definitions

**Comment by ChicknWing** [comment]
The old definition doesn't work. Need new one.
![image](https://user-images.githubusercontent.com/45902742/76597056-02254f80-64d6-11ea-854b-14e9630f0917.png)

**Comment by Pumpkinpie44** [comment]
Im getting same error with correct opcodes, where to get def files from ?

**Comment by Zoe975** [comment]
Ur Update works for me. Thank you :)
